"""Add RendimientoTecnicoSemaforoManual

Revision ID: 69d429c013ea
Revises: 002_maestros_dominio
Create Date: 2026-06-24 17:11:23.806531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '69d429c013ea'
down_revision: Union[str, Sequence[str], None] = '002_maestros_dominio'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rendimiento_tecnico_semaforos_manuales',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('codigo_sap', sa.String(length=50), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.Column('estado', sa.String(length=50), server_default=sa.text("'SIN_EVALUACION'"), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('usuario_actualiza_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("categoria IN ('SEGURIDAD', 'CALIDAD_CORTE', 'CUMPLIMIENTO_PROTOCOLOS', 'COMUNICACION_CLIENTE', 'DISCIPLINA_OPERACIONAL', 'ATENCION_CLIENTE')", name='chk_semaforo_manual_categoria'),
    sa.CheckConstraint("estado IN ('SIN_EVALUACION', 'CRITICO', 'RECUPERACION', 'ESTABLE', 'ALTO_DESEMPENO')", name='chk_semaforo_manual_estado'),
    sa.ForeignKeyConstraint(['usuario_actualiza_id'], ['control_usuarios.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_sap', 'categoria', name='uq_semaforo_manual_sap_categoria')
    )
    op.create_index('idx_semaforo_manual_sap', 'rendimiento_tecnico_semaforos_manuales', ['codigo_sap'], unique=False)
    op.alter_column('control_brigadas_diario', 'usuario',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('control_brigadas_diario', 'tipo_brigada',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('control_brigadas_diario', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('control_brigadas_diario', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_brigadas_fecha_zona'), table_name='control_brigadas_diario')
    op.create_index(op.f('ix_control_brigadas_diario_id'), 'control_brigadas_diario', ['id'], unique=False)
    op.alter_column('control_parametros_generales', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('control_parametros_generales', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_control_parametros_generales_id'), 'control_parametros_generales', ['id'], unique=False)
    op.alter_column('control_parametros_zona', 'brigadas_contrato',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('control_parametros_zona', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('control_parametros_zona', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_control_parametros_zona_id'), 'control_parametros_zona', ['id'], unique=False)
    op.alter_column('control_programacion_zona', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('control_programacion_zona', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_programacion_fecha_zona'), table_name='control_programacion_zona')
    op.drop_index(op.f('idx_programacion_zona_fecha_zona_tipo'), table_name='control_programacion_zona')
    op.create_index(op.f('ix_control_programacion_zona_id'), 'control_programacion_zona', ['id'], unique=False)
    op.alter_column('control_resultados_reales_zona', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('control_resultados_reales_zona', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('control_resultados_reales_zona_fecha_operacional_zona_key'), 'control_resultados_reales_zona', type_='unique')
    op.drop_index(op.f('idx_resultados_fecha_zona'), table_name='control_resultados_reales_zona')
    op.create_index(op.f('ix_control_resultados_reales_zona_id'), 'control_resultados_reales_zona', ['id'], unique=False)
    op.create_unique_constraint('uq_resultados_fecha_zona', 'control_resultados_reales_zona', ['fecha_operacional', 'zona'])
    op.drop_constraint(op.f('control_supervisor_comunas_zonas_supervisor_id_comuna_key'), 'control_supervisor_comunas_zonas', type_='unique')
    op.create_index(op.f('ix_control_supervisor_comunas_zonas_id'), 'control_supervisor_comunas_zonas', ['id'], unique=False)
    op.create_unique_constraint('uq_supervisor_comuna', 'control_supervisor_comunas_zonas', ['supervisor_id', 'comuna'])
    op.drop_constraint(op.f('control_supervisor_comunas_zonas_supervisor_id_fkey'), 'control_supervisor_comunas_zonas', type_='foreignkey')
    op.alter_column('control_supervisor_usuarios_sap', 'patente_habitual',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('control_supervisor_usuarios_sap', 'brigada',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('control_supervisor_usuarios_sap', 'pareja',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('control_supervisor_usuarios_sap', 'comuna_habitual',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.drop_constraint(op.f('control_supervisor_usuarios_sap_supervisor_id_codigo_sap_key'), 'control_supervisor_usuarios_sap', type_='unique')
    op.drop_constraint(op.f('control_supervisor_usuarios_sap_supervisor_id_cuenta_key'), 'control_supervisor_usuarios_sap', type_='unique')
    op.create_index(op.f('ix_control_supervisor_usuarios_sap_id'), 'control_supervisor_usuarios_sap', ['id'], unique=False)
    op.create_unique_constraint('uq_supervisor_cuenta', 'control_supervisor_usuarios_sap', ['supervisor_id', 'cuenta'])
    op.create_unique_constraint('uq_supervisor_sap', 'control_supervisor_usuarios_sap', ['supervisor_id', 'codigo_sap'])
    op.drop_constraint(op.f('control_supervisor_usuarios_sap_supervisor_id_fkey'), 'control_supervisor_usuarios_sap', type_='foreignkey')
    op.create_index(op.f('ix_control_supervisores_id'), 'control_supervisores', ['id'], unique=False)
    op.drop_index(op.f('ix_dim_comuna_nombre'), table_name='dim_comuna')
    op.drop_index(op.f('ix_dim_comuna_zona'), table_name='dim_comuna')
    op.create_index('idx_dim_comuna_zona', 'dim_comuna', ['zona_id'], unique=False)
    op.create_index(op.f('ix_dim_comuna_id'), 'dim_comuna', ['id'], unique=False)
    op.drop_index(op.f('ix_dim_sap_codigo'), table_name='dim_sap')
    op.drop_index(op.f('ix_dim_sap_cuenta'), table_name='dim_sap')
    op.create_index(op.f('ix_dim_sap_id'), 'dim_sap', ['id'], unique=False)
    op.drop_index(op.f('ix_dim_zona_nombre'), table_name='dim_zona')
    op.create_index(op.f('ix_dim_zona_id'), 'dim_zona', ['id'], unique=False)
    op.alter_column('reportes_cyr', 'estado',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'borrador'::character varying"))
    op.alter_column('reportes_cyr', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('reportes_cyr', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_reportes_fecha'), table_name='reportes_cyr')
    op.drop_constraint(op.f('reportes_cyr_fecha_operacional_key'), 'reportes_cyr', type_='unique')
    op.create_index(op.f('ix_reportes_cyr_fecha_operacional'), 'reportes_cyr', ['fecha_operacional'], unique=True)
    op.create_index(op.f('ix_reportes_cyr_id'), 'reportes_cyr', ['id'], unique=False)
    op.create_index(op.f('ix_rlt_supervisor_sap_id'), 'rlt_supervisor_sap', ['id'], unique=False)
    op.create_index(op.f('ix_rlt_supervisor_zona_id'), 'rlt_supervisor_zona', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rlt_supervisor_zona_id'), table_name='rlt_supervisor_zona')
    op.drop_index(op.f('ix_rlt_supervisor_sap_id'), table_name='rlt_supervisor_sap')
    op.drop_index(op.f('ix_reportes_cyr_id'), table_name='reportes_cyr')
    op.drop_index(op.f('ix_reportes_cyr_fecha_operacional'), table_name='reportes_cyr')
    op.create_unique_constraint(op.f('reportes_cyr_fecha_operacional_key'), 'reportes_cyr', ['fecha_operacional'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_reportes_fecha'), 'reportes_cyr', ['fecha_operacional'], unique=False)
    op.alter_column('reportes_cyr', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('reportes_cyr', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('reportes_cyr', 'estado',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'borrador'::character varying"))
    op.drop_index(op.f('ix_dim_zona_id'), table_name='dim_zona')
    op.create_index(op.f('ix_dim_zona_nombre'), 'dim_zona', ['nombre'], unique=False)
    op.drop_index(op.f('ix_dim_sap_id'), table_name='dim_sap')
    op.create_index(op.f('ix_dim_sap_cuenta'), 'dim_sap', ['cuenta'], unique=False)
    op.create_index(op.f('ix_dim_sap_codigo'), 'dim_sap', ['codigo_sap'], unique=False)
    op.drop_index(op.f('ix_dim_comuna_id'), table_name='dim_comuna')
    op.drop_index('idx_dim_comuna_zona', table_name='dim_comuna')
    op.create_index(op.f('ix_dim_comuna_zona'), 'dim_comuna', ['zona_id'], unique=False)
    op.create_index(op.f('ix_dim_comuna_nombre'), 'dim_comuna', ['nombre'], unique=False)
    op.drop_index(op.f('ix_control_supervisores_id'), table_name='control_supervisores')
    op.create_foreign_key(op.f('control_supervisor_usuarios_sap_supervisor_id_fkey'), 'control_supervisor_usuarios_sap', 'control_supervisores', ['supervisor_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_supervisor_sap', 'control_supervisor_usuarios_sap', type_='unique')
    op.drop_constraint('uq_supervisor_cuenta', 'control_supervisor_usuarios_sap', type_='unique')
    op.drop_index(op.f('ix_control_supervisor_usuarios_sap_id'), table_name='control_supervisor_usuarios_sap')
    op.create_unique_constraint(op.f('control_supervisor_usuarios_sap_supervisor_id_cuenta_key'), 'control_supervisor_usuarios_sap', ['supervisor_id', 'cuenta'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('control_supervisor_usuarios_sap_supervisor_id_codigo_sap_key'), 'control_supervisor_usuarios_sap', ['supervisor_id', 'codigo_sap'], postgresql_nulls_not_distinct=False)
    op.alter_column('control_supervisor_usuarios_sap', 'comuna_habitual',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=150),
               existing_nullable=True)
    op.alter_column('control_supervisor_usuarios_sap', 'pareja',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=150),
               existing_nullable=True)
    op.alter_column('control_supervisor_usuarios_sap', 'brigada',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=150),
               existing_nullable=True)
    op.alter_column('control_supervisor_usuarios_sap', 'patente_habitual',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.create_foreign_key(op.f('control_supervisor_comunas_zonas_supervisor_id_fkey'), 'control_supervisor_comunas_zonas', 'control_supervisores', ['supervisor_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_supervisor_comuna', 'control_supervisor_comunas_zonas', type_='unique')
    op.drop_index(op.f('ix_control_supervisor_comunas_zonas_id'), table_name='control_supervisor_comunas_zonas')
    op.create_unique_constraint(op.f('control_supervisor_comunas_zonas_supervisor_id_comuna_key'), 'control_supervisor_comunas_zonas', ['supervisor_id', 'comuna'], postgresql_nulls_not_distinct=False)
    op.drop_constraint('uq_resultados_fecha_zona', 'control_resultados_reales_zona', type_='unique')
    op.drop_index(op.f('ix_control_resultados_reales_zona_id'), table_name='control_resultados_reales_zona')
    op.create_index(op.f('idx_resultados_fecha_zona'), 'control_resultados_reales_zona', ['fecha_operacional', 'zona'], unique=False)
    op.create_unique_constraint(op.f('control_resultados_reales_zona_fecha_operacional_zona_key'), 'control_resultados_reales_zona', ['fecha_operacional', 'zona'], postgresql_nulls_not_distinct=False)
    op.alter_column('control_resultados_reales_zona', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('control_resultados_reales_zona', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_control_programacion_zona_id'), table_name='control_programacion_zona')
    op.create_index(op.f('idx_programacion_zona_fecha_zona_tipo'), 'control_programacion_zona', ['fecha_operacional', 'zona', 'tipo_brigada'], unique=False)
    op.create_index(op.f('idx_programacion_fecha_zona'), 'control_programacion_zona', ['fecha_operacional', 'zona'], unique=False)
    op.alter_column('control_programacion_zona', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('control_programacion_zona', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_control_parametros_zona_id'), table_name='control_parametros_zona')
    op.alter_column('control_parametros_zona', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('control_parametros_zona', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('control_parametros_zona', 'brigadas_contrato',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_control_parametros_generales_id'), table_name='control_parametros_generales')
    op.alter_column('control_parametros_generales', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('control_parametros_generales', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_control_brigadas_diario_id'), table_name='control_brigadas_diario')
    op.create_index(op.f('idx_brigadas_fecha_zona'), 'control_brigadas_diario', ['fecha_operacional', 'zona'], unique=False)
    op.alter_column('control_brigadas_diario', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('control_brigadas_diario', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('control_brigadas_diario', 'tipo_brigada',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('control_brigadas_diario', 'usuario',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.drop_index('idx_semaforo_manual_sap', table_name='rendimiento_tecnico_semaforos_manuales')
    op.drop_table('rendimiento_tecnico_semaforos_manuales')
    # ### end Alembic commands ###
