"""Add RendimientoTecnicoSemaforoManual

Revision ID: 69d429c013ea
Revises: 002_maestros_dominio
Create Date: 2026-06-24 17:11:23.806531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '69d429c013ea'
down_revision: Union[str, Sequence[str], None] = '002_maestros_dominio'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rendimiento_tecnico_semaforos_manuales',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('codigo_sap', sa.String(length=50), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.Column('estado', sa.String(length=50), server_default=sa.text("'SIN_EVALUACION'"), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('usuario_actualiza_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("categoria IN ('SEGURIDAD', 'CALIDAD_CORTE', 'CUMPLIMIENTO_PROTOCOLOS', 'COMUNICACION_CLIENTE', 'DISCIPLINA_OPERACIONAL', 'ATENCION_CLIENTE')", name='chk_semaforo_manual_categoria'),
    sa.CheckConstraint("estado IN ('SIN_EVALUACION', 'CRITICO', 'RECUPERACION', 'ESTABLE', 'ALTO_DESEMPENO')", name='chk_semaforo_manual_estado'),
    sa.ForeignKeyConstraint(['usuario_actualiza_id'], ['control_usuarios.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_sap', 'categoria', name='uq_semaforo_manual_sap_categoria')
    )
    op.create_index('idx_semaforo_manual_sap', 'rendimiento_tecnico_semaforos_manuales', ['codigo_sap'], unique=False)
    # Se omiten las alteraciones de columnas y borrado de índices autogenerados
    # para evitar problemas de consistencia con la base de datos de producción.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_semaforo_manual_sap', table_name='rendimiento_tecnico_semaforos_manuales')
    op.drop_table('rendimiento_tecnico_semaforos_manuales')
    # ### end Alembic commands ###
