"""Create rendimiento_tecnico_recomendaciones table

Revision ID: e88cd9c1e280
Revises: 004_add_brigada_pareja_diaria
Create Date: 2026-06-26 10:46:57.358300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e88cd9c1e280'
down_revision: Union[str, Sequence[str], None] = '004_add_brigada_pareja_diaria'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rendimiento_tecnico_recomendaciones',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('codigo_sap', sa.String(length=50), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=False),
    sa.Column('prioridad', sa.String(length=10), server_default=sa.text("'MEDIA'"), nullable=False),
    sa.Column('estado_accion', sa.String(length=20), server_default=sa.text("'PENDIENTE'"), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("estado_accion IN ('PENDIENTE', 'EN_CURSO', 'COMPLETADO', 'CANCELADO')", name='chk_recomendacion_estado_accion'),
    sa.CheckConstraint("prioridad IN ('ALTA', 'MEDIA', 'BAJA')", name='chk_recomendacion_prioridad'),
    sa.ForeignKeyConstraint(['usuario_id'], ['control_usuarios.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_recomendacion_sap', 'rendimiento_tecnico_recomendaciones', ['codigo_sap'], unique=False)
    op.create_index(op.f('ix_rendimiento_tecnico_recomendaciones_codigo_sap'), 'rendimiento_tecnico_recomendaciones', ['codigo_sap'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rendimiento_tecnico_recomendaciones_codigo_sap'), table_name='rendimiento_tecnico_recomendaciones')
    op.drop_index('idx_recomendacion_sap', table_name='rendimiento_tecnico_recomendaciones')
    op.drop_table('rendimiento_tecnico_recomendaciones')
    # ### end Alembic commands ###
