"""Create rendimiento_tecnico_recomendaciones table

Revision ID: e88cd9c1e280
Revises: 004_add_brigada_pareja_diaria
Create Date: 2026-06-26 10:46:57.358300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e88cd9c1e280'
down_revision: Union[str, Sequence[str], None] = '004_add_brigada_pareja_diaria'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute(sa.text("""
        CREATE TABLE IF NOT EXISTS rendimiento_tecnico_recomendaciones (
            id                  BIGSERIAL PRIMARY KEY,
            codigo_sap          VARCHAR(50) NOT NULL,
            comentario          TEXT NOT NULL,
            prioridad           VARCHAR(10) NOT NULL DEFAULT 'MEDIA',
            estado_accion       VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE',
            usuario_id          INTEGER NOT NULL REFERENCES control_usuarios(id) ON DELETE RESTRICT,
            created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT chk_recomendacion_prioridad
                CHECK (prioridad IN ('ALTA', 'MEDIA', 'BAJA')),
            CONSTRAINT chk_recomendacion_estado_accion
                CHECK (estado_accion IN ('PENDIENTE', 'EN_CURSO', 'COMPLETADO', 'CANCELADO'))
        )
    """))
    op.execute(sa.text("CREATE INDEX IF NOT EXISTS idx_recomendacion_sap ON rendimiento_tecnico_recomendaciones(codigo_sap)"))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rendimiento_tecnico_recomendaciones_codigo_sap'), table_name='rendimiento_tecnico_recomendaciones')
    op.drop_index('idx_recomendacion_sap', table_name='rendimiento_tecnico_recomendaciones')
    op.drop_table('rendimiento_tecnico_recomendaciones')
    # ### end Alembic commands ###
